---
- name: Clone provided elixir repositories
  git:
    repo="{{ item }}"
    dest="{{ git_clone_path }}/{{ item | basename }}"
    accept_hostkey=yes
    key_file="{{ phoenix_git_key_path }}"
  with_items: "{{ phoenix_repos }}"
  sudo: yes
  sudo_user: "{{ phoenix_user }}"

- name: Get dependencies of elixir repos
  command: "{{ item.1 }}"
  args:
    chdir: "{{ git_clone_path }}/{{ item.0 | basename }}"
  with_nested:
    - "{{ phoenix_repos }}"
    - "{{ phoenix_commands }}"
  sudo: yes
  sudo_user: "{{ phoenix_user }}"

- name: Run phoenix service
  shell: "nohup mix phoenix.server >> /tmp/phoenix_server.log 2>&1&"
  args:
    chdir: "{{ git_clone_path }}/{{ item | basename }}"
  with_items:
    - "{{ phoenix_repos }}"
  sudo: yes
  sudo_user: "{{ phoenix_user }}"
